### ISSUE TITLE
Application doesn't build

### ISSUE THREAD

**Issue by vivaladav** [tanius/qml-sql-example#1]
I tried to build your example in Qt Creator 4.12.1, but the build fails because it can't find QApplication.

To fix it just add "widgets" to the QT variable in the _.pro_ file like this:

`QT += core gui qml sql widgets`

**Comment by tanius** [comment]
Thank you for testing it! :) It seems I didn't try a clean build after removing the `widgets` QML module.

Turns out the `QApplication` include was not needed. It builds now without that.
